version: '3.8'
services:
  apacheds:
    build: ./apacheds
    container_name: apacheds
    ports:
      - "10389:10389"
      - "10636:10636"
      - "11001:11001"
    volumes:
      - apacheds_data:/var/apacheds
  app:
    build: ./app
    container_name: flask_app
    environment:
      LDAP_HOST: apacheds
      LDAP_PORT: 10389
      LDAP_BIND_DN: uid=admin,ou=system
      LDAP_PASSWORD: secret
      BASE_DN: dc=example,dc=com
    depends_on:
      - apacheds
    ports:
      - "5034:5034"
volumes:
  apacheds_data:
